name: release
on:
  workflow_dispatch:
    inputs:
      part:
        type: choice
        options: [patch, minor, major]
        default: patch
      repo:
        type: choice
        options: [testpypi, pypi]
        default: testpypi

jobs:
  rel:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: astral-sh/setup-uv@v3

      - name: Bump version, commit, tag
        run: |
          uv version --bump "${{ inputs.part }}"
          git add pyproject.toml
          git commit -m "bump: ${{ inputs.part }}"
          git tag "v$(uv version)"
          git push && git push --tags

      - name: Build
        run: |
          uv run python -m pip install -U build
          uv run python -m build

      - name: Publish (TestPyPI)
        if: inputs.repo == 'testpypi'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          uvx twine check dist/*
          uvx twine upload --repository testpypi dist/*

      - name: Publish (PyPI)
        if: inputs.repo == 'pypi'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          uvx twine check dist/*
          uvx twine upload dist/*
